/**
 * Wire-format parity tests.
 *
 * These tests are the most important in the package. They prove that
 * EventBuilder.build() — given the same inputs as the Ruby agent —
 * produces a JSON document byte-for-byte identical to what the Ruby
 * agent ships.
 *
 * Fixtures are generated by `ez_logs_agent/bin/generate_parity_fixtures.rb`
 * and copied into `tests/parity/fixtures/`. To regenerate:
 *
 *   cd ez_logs_agent && bundle exec ruby bin/generate_parity_fixtures.rb
 *   cp ez_logs_agent/spec/fixtures/parity/*.json \
 *      ez_logs_agent_nextjs/tests/parity/fixtures/
 *
 * Each test reconstructs the inputs that produced the Ruby fixture and
 * runs them through the Node EventBuilder. Output must match the fixture
 * via `JSON.stringify` (string equality), not just deep equality —
 * key ordering matters, and the Ruby pretty-printed fixture is normalized
 * via JSON.parse + JSON.stringify before comparison.
 */

import { readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { build, type BuildInput, type Event } from "../../src/event-builder.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = join(__dirname, "fixtures");
const FIXED_TIMESTAMP = "2026-01-15T12:00:00.000Z";
const FIXED_CORRELATION_ID = "ezl_1737000000000_deadbeef";

function loadFixture(name: string): Event {
  const raw = readFileSync(join(FIXTURES_DIR, `${name}.json`), "utf8");
  return JSON.parse(raw) as Event;
}

function assertParity(input: BuildInput, fixtureName: string): void {
  const built = build(input);
  const fixture = loadFixture(fixtureName);
  // Step 1: deep equal (catches data drift)
  expect(built).toEqual(fixture);
  // Step 2: byte-for-byte JSON equality (catches key-order drift)
  expect(JSON.stringify(built)).toBe(JSON.stringify(fixture));
}

describe("Wire-format parity vs Ruby agent — HTTP", () => {
  it("http_get_simple matches Ruby fixture", () => {
    assertParity(
      {
        source_type: "http_request",
        source_data: {
          method: "GET",
          path: "/api/users",
          status_code: 200,
          controller: "app/api/users",
          action: "GET",
          format: "json",
          user_agent: "Mozilla/5.0",
          remote_ip: "127.0.0.1",
        },
        outcome: "success",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [],
        context: null,
        duration_ms: 124,
        timestamp: FIXED_TIMESTAMP,
      },
      "http_get_simple",
    );
  });

  it("http_post_with_params_sanitized matches Ruby fixture (filters password + api_key)", () => {
    assertParity(
      {
        source_type: "http_request",
        source_data: {
          method: "POST",
          path: "/api/users",
          status_code: 201,
          controller: "app/api/users",
          action: "POST",
          format: "json",
          user_agent: "Mozilla/5.0",
          remote_ip: "127.0.0.1",
          request_params: {
            email: "alice@example.com",
            password: "hunter2",
            api_key: "sk_live_xxx",
            name: "Alice",
          },
        },
        outcome: "success",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [],
        context: { actor: { id: "42", label: "alice@example.com" } },
        duration_ms: 230,
        timestamp: FIXED_TIMESTAMP,
      },
      "http_post_with_params_sanitized",
    );
  });

  it("http_failure_4xx matches Ruby fixture", () => {
    assertParity(
      {
        source_type: "http_request",
        source_data: {
          method: "GET",
          path: "/api/widgets/missing",
          status_code: 404,
          controller: "app/api/widgets/[id]",
          action: "GET",
          format: "json",
          user_agent: "curl/8.4.0",
          remote_ip: "203.0.113.7",
        },
        outcome: "failure",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [],
        context: null,
        duration_ms: 12,
        error_message: "HTTP 404",
        timestamp: FIXED_TIMESTAMP,
      },
      "http_failure_4xx",
    );
  });

  it("http_failure_exception matches Ruby fixture", () => {
    assertParity(
      {
        source_type: "http_request",
        source_data: {
          method: "POST",
          path: "/api/orders",
          status_code: 500,
          controller: "app/api/orders",
          action: "POST",
          format: "json",
          user_agent: "Mozilla/5.0",
          remote_ip: "10.0.0.5",
        },
        outcome: "failure",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [],
        context: null,
        duration_ms: 88,
        error_message: "RuntimeError: payment provider unreachable",
        timestamp: FIXED_TIMESTAMP,
      },
      "http_failure_exception",
    );
  });
});

describe("Wire-format parity vs Ruby agent — database", () => {
  it("db_create matches Ruby fixture", () => {
    assertParity(
      {
        source_type: "database_callback",
        source_data: { model_class: "User", operation: "create" },
        outcome: "success",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [{ resource_type: "User", resource_id: "42" }],
        context: {
          initial_attributes: {
            email: "alice@example.com",
            name: "Alice",
            role: "customer",
          },
          display_name: "alice@example.com",
        },
        duration_ms: null,
        timestamp: FIXED_TIMESTAMP,
      },
      "db_create",
    );
  });

  it("db_create_filters_sensitive matches Ruby fixture", () => {
    assertParity(
      {
        source_type: "database_callback",
        source_data: { model_class: "User", operation: "create" },
        outcome: "success",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [{ resource_type: "User", resource_id: "43" }],
        context: {
          initial_attributes: {
            email: "bob@example.com",
            password_hash: "$argon2id$...",
            api_key: "sk_live_yyy",
            name: "Bob",
          },
          display_name: "bob@example.com",
        },
        duration_ms: null,
        timestamp: FIXED_TIMESTAMP,
      },
      "db_create_filters_sensitive",
    );
  });

  it("db_update_with_changes matches Ruby fixture", () => {
    assertParity(
      {
        source_type: "database_callback",
        source_data: { model_class: "Order", operation: "update" },
        outcome: "success",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [{ resource_type: "Order", resource_id: "1001" }],
        context: {
          changes: [
            { attribute: "status", from: "pending", to: "shipped" },
            { attribute: "tracking_number", from: null, to: "1Z999AA10123456784" },
          ],
          display_name: "ORD-1001",
        },
        duration_ms: null,
        timestamp: FIXED_TIMESTAMP,
      },
      "db_update_with_changes",
    );
  });

  it("db_destroy matches Ruby fixture", () => {
    assertParity(
      {
        source_type: "database_callback",
        source_data: { model_class: "Cart", operation: "destroy" },
        outcome: "success",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [{ resource_type: "Cart", resource_id: "777" }],
        context: { display_name: "Cart #777" },
        duration_ms: null,
        timestamp: FIXED_TIMESTAMP,
      },
      "db_destroy",
    );
  });
});

describe("Wire-format parity vs Ruby agent — background jobs", () => {
  it("job_success matches Ruby fixture", () => {
    assertParity(
      {
        source_type: "background_job",
        source_data: {
          job_class: "ChargeCardJob",
          job_id: "01J9XYZ12345",
          queue: "default",
          retry_count: 0,
        },
        outcome: "success",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [],
        context: null,
        duration_ms: 412,
        timestamp: FIXED_TIMESTAMP,
      },
      "job_success",
    );
  });

  it("job_failure matches Ruby fixture", () => {
    assertParity(
      {
        source_type: "background_job",
        source_data: {
          job_class: "SendEmailJob",
          job_id: "01J9XYZABCDE",
          queue: "mailers",
          retry_count: 2,
        },
        outcome: "failure",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [],
        context: null,
        duration_ms: 1503,
        error_message: "Net::SMTPAuthenticationError: 535 Authentication failed",
        timestamp: FIXED_TIMESTAMP,
      },
      "job_failure",
    );
  });
});

describe("Wire-format parity vs Ruby agent — sanitization edge cases", () => {
  it("sanitize_nested_and_array filters nested + array-of-object sensitive keys", () => {
    assertParity(
      {
        source_type: "http_request",
        source_data: {
          method: "POST",
          path: "/api/keys/rotate",
          status_code: 200,
          request_params: {
            user: {
              email: "carol@example.com",
              credit_card: "4242424242424242",
            },
            tokens: [
              { name: "ci", secret: "wow" },
              { name: "prod", secret: "such-secret" },
            ],
          },
        },
        outcome: "success",
        correlation_id: FIXED_CORRELATION_ID,
        resource_ids: [],
        context: null,
        duration_ms: 50,
        timestamp: FIXED_TIMESTAMP,
      },
      "sanitize_nested_and_array",
    );
  });
});

describe("Wire-format parity — fixture inventory", () => {
  it("every fixture file is exercised by a test in this suite", () => {
    const onDisk = readdirSync(FIXTURES_DIR)
      .filter((f) => f.endsWith(".json"))
      .map((f) => f.replace(/\.json$/, ""))
      .sort();
    // Hand-rolled list — update whenever a fixture is added.
    const exercised = [
      "db_create",
      "db_create_filters_sensitive",
      "db_destroy",
      "db_update_with_changes",
      "http_failure_4xx",
      "http_failure_exception",
      "http_get_simple",
      "http_post_with_params_sanitized",
      "job_failure",
      "job_success",
      "sanitize_nested_and_array",
    ].sort();
    expect(onDisk).toEqual(exercised);
  });
});
